# Generated by Django 3.1.6 on 2021-02-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210214_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
