# Generated by Django 3.1.6 on 2021-02-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210214_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Kullanıcı Profili', 'verbose_name_plural': 'Kullanıcı Profilleri'},
        ),
    ]
