# Generated by Django 3.1.6 on 2021-02-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True, verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name_lname',
            field=models.CharField(max_length=200, null=True, verbose_name='Ad-Soyad'),
        ),
    ]
